name: master

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./app
        run: yarn

      - name: Check formatting
        working-directory: ./app
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./app
        run: yarn

      - name: Build application
        working-directory: ./app
        run: yarn build
