version: '3.7'

services:
  app:
    restart: always
    build: ./app
    env_file: ./app/.env.local
    container_name: startup-dir
    command: yarn dev
    volumes:
      - ./app/app/startup-dir
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: db
    ports:
      - '27017:27017'

volumes:
  node_modules:
