version: '3.7'

services:
  app:
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    env_file: ./app/.env.local
    container_name: startup-dir
    command: yarn dev
    volumes:
      - ./app:/app/startup_directory
      - /app/startup_directory/node_modules
      - /app/startup_directory/.next
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: db
    ports:
      - '27017:27017'

